{% set version = "0.3.0" %}

package:
  name: descartes-light
  version: {{ version }}

source:
  - git_url: https://github.com/swri-robotics/descartes_light.git
    git_rev: {{ version }}
    folder: src

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gtest
    - gmock
    - cmake
    - ninja # [win]
    - make # [linux]
    - ros-industrial-cmake-boilerplate
  host:
    - eigen
    - console_bridge
    - boost-cpp
    - llvm-openmp
  run:
    - eigen
    - console_bridge
    - boost-cpp
    - llvm-openmp

test:
  commands:
    - test -f ${PREFIX}/include/descartes_light/core/solver.h  # [unix]
    - test -f ${PREFIX}/lib/libdescartes_light.so  # [unix]
    - test -f ${PREFIX}/lib/cmake/descartes_light/descartes_light-config.cmake # [unix]
    - if not exist %LIBRARY_PREFIX%\include\descartes_light\core\solver.h (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\descartes_light.lib (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\descartes_light.dll (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\descartes_light\descartes_light-config.cmake (exit 1)  # [win]

build:
  number: 4

about:
  home: https://github.com/swri-robotics/descartes_light
  summary: Library for generation motion plans for process toolpaths